'use client';

import { useState, useEffect } from 'react';
import clsx from 'clsx';
import { slugify } from '../utils/helpers';
import { INPUT_CLASSES, BUTTON_PRIMARY_CLASSES } from '../utils/constants';

export interface ArticleMetadata {
  slug: string;
  title: string;
  description: string;
  date: string;
  image: string;
  canonicalUrl: string;
  tags: string[];
  readingTime: string;
  faqs: Array<{ question: string; answer: string }>;
  heroImage: string;
  draft?: boolean;
}

interface ArticleMetadataPanelProps {
  metadata: ArticleMetadata;
  onChange: (metadata: ArticleMetadata) => void;
  isOpen: boolean;
  onClose: () => void;
  isNewFile?: boolean;
  articleContent?: string; // HTML content for AI tag generation
  onGetArticleContent?: () => string; // Function to get fresh article content
}

export default function ArticleMetadataPanel({
  metadata,
  onChange,
  isOpen,
  onClose,
  isNewFile = false,
  articleContent,
  onGetArticleContent,
}: ArticleMetadataPanelProps) {
  const [localMetadata, setLocalMetadata] = useState<ArticleMetadata>(metadata);
  const [newTag, setNewTag] = useState('');
  const [newFaq, setNewFaq] = useState({ question: '', answer: '' });
  const [autoGeneratedSlug, setAutoGeneratedSlug] = useState<string | null>(null);
  const [isGeneratingTags, setIsGeneratingTags] = useState(false);

  // Sync local metadata when prop changes (e.g., when title or heroImage is updated from main editor)
  useEffect(() => {
    const prevSlug = localMetadata.slug;
    setLocalMetadata(metadata);
    
    // If slug changed and matches what would be auto-generated from title, track it
    if (isNewFile && metadata.title && metadata.slug) {
      const expectedSlug = slugify(metadata.title);
      if (metadata.slug === expectedSlug) {
        // Slug matches auto-generated pattern, track it
        if (!autoGeneratedSlug || metadata.slug === autoGeneratedSlug) {
          setAutoGeneratedSlug(metadata.slug);
        }
      } else if (prevSlug === autoGeneratedSlug && metadata.slug !== autoGeneratedSlug) {
        // Slug was manually changed, stop auto-generating
        setAutoGeneratedSlug(null);
      }
    } else if (autoGeneratedSlug && metadata.slug !== autoGeneratedSlug) {
      // Slug doesn't match auto-generated slug, it was manually changed
      setAutoGeneratedSlug(null); // Stop auto-generating
    }
  }, [metadata]);

  const updateField = (field: keyof ArticleMetadata, value: any) => {
    const updated = { ...localMetadata, [field]: value };
    setLocalMetadata(updated);
    onChange(updated);
  };

  const addTag = () => {
    if (newTag.trim()) {
      const updated = {
        ...localMetadata,
        tags: [...localMetadata.tags, newTag.trim()],
      };
      setLocalMetadata(updated);
      onChange(updated);
      setNewTag('');
    }
  };

  const removeTag = (index: number) => {
    const updated = {
      ...localMetadata,
      tags: localMetadata.tags.filter((_, i) => i !== index),
    };
    setLocalMetadata(updated);
    onChange(updated);
  };

  // Generate tags using AI
  const generateTagsWithAI = async () => {
    if (!localMetadata.title) {
      return;
    }

    setIsGeneratingTags(true);

    try {
      // Get fresh content - prefer the function if available, otherwise use prop
      const content = onGetArticleContent ? onGetArticleContent() : (articleContent || "");

      const response = await fetch("/api/openai/generate-article-tags", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: localMetadata.title,
          description: localMetadata.description,
          content: content,
        }),
      });

      const data = await response.json();

      if (data.success && data.tags) {
        // Replace all existing tags with the new ones
        const updated = {
          ...localMetadata,
          tags: data.tags,
        };
        setLocalMetadata(updated);
        onChange(updated);
      }
    } catch (err: any) {
      console.error("Failed to generate tags:", err);
    } finally {
      setIsGeneratingTags(false);
    }
  };

  const addFaq = () => {
    if (newFaq.question.trim() && newFaq.answer.trim()) {
      const updated = {
        ...localMetadata,
        faqs: [...localMetadata.faqs, { ...newFaq }],
      };
      setLocalMetadata(updated);
      onChange(updated);
      setNewFaq({ question: '', answer: '' });
    }
  };

  const removeFaq = (index: number) => {
    const updated = {
      ...localMetadata,
      faqs: localMetadata.faqs.filter((_, i) => i !== index),
    };
    setLocalMetadata(updated);
    onChange(updated);
  };

  const updateFaq = (index: number, field: 'question' | 'answer', value: string) => {
    const updated = {
      ...localMetadata,
      faqs: localMetadata.faqs.map((faq, i) =>
        i === index ? { ...faq, [field]: value } : faq
      ),
    };
    setLocalMetadata(updated);
    onChange(updated);
  };

  return (
    <>
      {/* Backdrop */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black/20 z-40 transition-opacity"
          onClick={onClose}
        />
      )}

      {/* Sidebar */}
      <div
        className={clsx(
          'fixed right-0 top-0 h-full w-full max-w-md bg-white shadow-xl z-50 transform transition-transform duration-300 ease-in-out overflow-y-auto',
          isOpen ? 'translate-x-0' : 'translate-x-full'
        )}
      >
        <div className="sticky top-0 bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between z-10">
          <h2 className="text-xl font-semibold text-gray-900">Article Settings</h2>
          <button
            onClick={onClose}
            className="p-2 hover:bg-gray-100 rounded-md transition-colors"
            aria-label="Close sidebar"
          >
            <svg
              className="w-5 h-5 text-gray-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <div className="p-6 space-y-6">
          {/* Slug */}
          <div>
            <label htmlFor="metadata-slug" className="block text-sm font-medium text-gray-700 mb-2">
              Slug
            </label>
            <input
              id="metadata-slug"
              type="text"
              value={localMetadata.slug}
              onChange={(e) => {
                const newSlug = e.target.value;
                // If user manually changes slug, stop auto-generating
                if (newSlug !== autoGeneratedSlug) {
                  setAutoGeneratedSlug(null);
                }
                updateField('slug', newSlug);
              }}
              placeholder="article-slug"
              className={INPUT_CLASSES}
            />
          </div>

          {/* Title */}
          <div>
            <label htmlFor="metadata-title" className="block text-sm font-medium text-gray-700 mb-2">
              Title
            </label>
            <input
              id="metadata-title"
              type="text"
              value={localMetadata.title}
              onChange={(e) => {
                const newTitle = e.target.value;
                // Auto-generate slug from title only for new files
                let newSlug = localMetadata.slug;
                if (isNewFile && (!newSlug || newSlug === autoGeneratedSlug)) {
                  const generatedSlug = slugify(newTitle);
                  newSlug = generatedSlug;
                  setAutoGeneratedSlug(generatedSlug);
                  // Update both title and slug together
                  const updated = { ...localMetadata, title: newTitle, slug: generatedSlug };
                  setLocalMetadata(updated);
                  onChange(updated);
                } else {
                  updateField('title', newTitle);
                }
              }}
              placeholder="Article Title"
              className={INPUT_CLASSES}
            />
          </div>

          {/* Description */}
          <div>
            <label htmlFor="metadata-description" className="block text-sm font-medium text-gray-700 mb-2">
              Description
            </label>
            <textarea
              id="metadata-description"
              value={localMetadata.description}
              onChange={(e) => updateField('description', e.target.value)}
              placeholder="Article description"
              rows={3}
              className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent resize-none"
            />
          </div>

          {/* Date */}
          <div>
            <label htmlFor="metadata-date" className="block text-sm font-medium text-gray-700 mb-2">
              Date
            </label>
            <input
              id="metadata-date"
              type="date"
              value={localMetadata.date}
              onChange={(e) => updateField('date', e.target.value)}
              className={INPUT_CLASSES}
            />
          </div>

          {/* Hero Image */}
          <div>
            <label htmlFor="metadata-hero-image" className="block text-sm font-medium text-gray-700 mb-2">
              Hero Image URL
            </label>
            <input
              id="metadata-hero-image"
              type="url"
              value={localMetadata.heroImage}
              onChange={(e) => updateField('heroImage', e.target.value)}
              placeholder="https://example.com/image.jpg"
              className={INPUT_CLASSES}
            />
            {localMetadata.heroImage && (
              <div className="mt-2 w-full aspect-video rounded-md border border-gray-200 overflow-hidden">
                <img
                  src={localMetadata.heroImage}
                  alt="Hero preview"
                  className="w-full h-full object-cover"
                  onError={(e) => {
                    (e.target as HTMLImageElement).style.display = 'none';
                  }}
                />
              </div>
            )}
          </div>

          {/* Canonical URL */}
          <div>
            <label htmlFor="metadata-canonical-url" className="block text-sm font-medium text-gray-700 mb-2">
              Canonical URL
            </label>
            <input
              id="metadata-canonical-url"
              type="url"
              value={localMetadata.canonicalUrl}
              onChange={(e) => updateField('canonicalUrl', e.target.value)}
              placeholder="https://example.com/article"
              className={INPUT_CLASSES}
            />
          </div>

          {/* Reading Time */}
          <div>
            <label htmlFor="metadata-reading-time" className="block text-sm font-medium text-gray-700 mb-2">
              Reading Time
            </label>
            <input
              id="metadata-reading-time"
              type="text"
              value={localMetadata.readingTime}
              onChange={(e) => updateField('readingTime', e.target.value)}
              placeholder="5 min read"
              className={INPUT_CLASSES}
            />
          </div>

          {/* Draft */}
          <div>
            <label htmlFor="metadata-draft" className="flex items-center gap-2 cursor-pointer">
              <input
                id="metadata-draft"
                type="checkbox"
                checked={localMetadata.draft || false}
                onChange={(e) => updateField('draft', e.target.checked)}
                className="w-4 h-4 text-gray-900 border-gray-300 rounded focus:ring-2 focus:ring-gray-900"
              />
              <span className="text-sm font-medium text-gray-700">Draft</span>
            </label>
            <p className="mt-1 text-xs text-gray-500">
              Mark this article as a draft
            </p>
          </div>

          {/* Tags */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Tags
            </label>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={newTag}
                onChange={(e) => setNewTag(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') {
                    e.preventDefault();
                    addTag();
                  }
                }}
                placeholder="Add tag"
                className="flex-1 px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
              />
              <button
                onClick={addTag}
                className="px-4 py-2 bg-gray-900 text-white rounded-md text-sm font-medium hover:bg-gray-800 transition-colors"
              >
                Add
              </button>
              <button
                onClick={generateTagsWithAI}
                disabled={isGeneratingTags || !localMetadata.title}
                className="px-4 py-2 bg-blue-600 text-white rounded-md text-sm font-medium hover:bg-blue-700 transition-colors disabled:bg-gray-400 disabled:cursor-not-allowed"
                title="Generate tags with AI"
              >
                {isGeneratingTags ? "Generating..." : "Generate with AI"}
              </button>
            </div>
            <div className="flex flex-wrap gap-2">
              {localMetadata.tags.map((tag, index) => (
                <span
                  key={index}
                  className="inline-flex items-center gap-1 px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm"
                >
                  {tag}
                  <button
                    onClick={() => removeTag(index)}
                    className="hover:text-gray-900"
                    aria-label={`Remove ${tag}`}
                  >
                    ×
                  </button>
                </span>
              ))}
            </div>
          </div>

          {/* FAQs */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              FAQs
            </label>
            <div className="space-y-4 mb-4">
              {localMetadata.faqs.map((faq, index) => (
                <div
                  key={index}
                  className="p-4 border border-gray-200 rounded-md bg-gray-50"
                >
                  <div className="flex items-start justify-between mb-2">
                    <span className="text-xs font-medium text-gray-500">
                      FAQ #{index + 1}
                    </span>
                    <button
                      onClick={() => removeFaq(index)}
                      className="text-red-600 hover:text-red-800 text-sm"
                      aria-label="Remove FAQ"
                    >
                      Remove
                    </button>
                  </div>
                  <input
                    type="text"
                    value={faq.question}
                    onChange={(e) => updateFaq(index, 'question', e.target.value)}
                    placeholder="Question"
                    className="w-full px-3 py-2 mb-2 border border-gray-300 rounded-md text-sm bg-white focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent"
                  />
                  <textarea
                    value={faq.answer}
                    onChange={(e) => updateFaq(index, 'answer', e.target.value)}
                    placeholder="Answer"
                    rows={2}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm bg-white focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent resize-none"
                  />
                </div>
              ))}
            </div>
            <div className="space-y-2 p-4 border-2 border-dashed border-gray-300 rounded-md">
              <input
                type="text"
                value={newFaq.question}
                onChange={(e) => setNewFaq({ ...newFaq, question: e.target.value })}
                placeholder="New question"
                className={INPUT_CLASSES}
              />
              <textarea
                value={newFaq.answer}
                onChange={(e) => setNewFaq({ ...newFaq, answer: e.target.value })}
                placeholder="New answer"
                rows={2}
                className="w-full px-3 py-2 border border-gray-300 rounded-md text-sm focus:outline-none focus:ring-2 focus:ring-gray-900 focus:border-transparent resize-none"
              />
              <button
                onClick={addFaq}
                className={BUTTON_PRIMARY_CLASSES}
              >
                Add FAQ
              </button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}

